version: '3.8'

services:
  bb_db:
    image: postgres:17.4
    container_name: bbdb_container
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bb_db
    ports:
      - "0.0.0.0:4326:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: